#!/bin/bash
CropID='XXXXXX'
Secret='XXXXXX'
GURL="https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=$CropID&corpsecret=$Secret"
Gtoken=$(/usr/bin/curl -s -G $GURL | awk -F\" '{print $10}')
PURL="https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=$Gtoken"
#
function body() {
local int AppID=XXXXXX
local UserID="@all"                  
local PartyID=XXXXXX                           
local Msg=$(echo "$@" | cut -d" " -f3-)   
printf '{\n'
printf '\t"touser": "'"$UserID"\"",\n"
printf '\t"toparty": "'"$PartyID"\"",\n"
printf '\t"msgtype": "text",\n'
printf '\t"agentid": "'"$AppID"\"",\n"
printf '\t"text": {\n'
printf '\t\t"content": "'"$Msg"\""\n"
printf '\t},\n'
printf '\t"safe":"0"\n'
printf '}\n'
}
/usr/bin/curl --data-ascii "$(body $! $2 $3)" $PURL


【Operations】
默认主题：
' '
默认信息：
\n 主机名称：{HOST.NAME}\n
告警时间：{EVENT.DATE} {EVENT.TIME}\n
告警内容：{TRIGGER.NAME}\n
当前数值：{ITEM.LASTVALUE}
 
【Recovery Operations】
默认主题：
' '
默认信息：
\n 主机名称：{HOST.NAME}\n
告警内容：{TRIGGER.NAME}\n
当前数值：{ITEM.LASTVALUE}\n
是否恢复：{TRIGGER.STATUS}
